### ISSUE TITLE
Great job! Just one small tweak for the iPhone 4S in Safari

### ISSUE THREAD

**Issue by nep2ne** [Jowens96/confectionery-website-prototype#2]
Well done, that's a good looking website! It would be nice if the nav linked to the actual sections on the page, but otherwise it's great.

**Comment by Jowens96** [comment]
Thanks!

Here are some issues I noticed for myself in Firefox:
The hexagonal image in the hours section becomes misplaced at 608px. It stays wonky through till 1440px. It seems to push the Location h2 out of place. It could be a float or positioning issue.

**Comment by Jowens96** [comment]
I've added anchors that direct the navigation to the appropriate sections of the page.
